spring:
  application:
    name: eureka-server-nutrition
  boot:
    admin:
      context-path: /admin
server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server-nutrition
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5


management:
  endpoints:
    web:
      exposure:
        include: "*"

